name: Android

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build & Verify Android Release
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./mob

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Static Analysis
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run Unit Tests
        run: flutter test

      - name: Build Android APK (Release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenSpark-v0.1.0-Beta-APK
          path: mob/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7